### ISSUE TITLE
can you add https://www.reddit.com/r/AmItheAsshole/

### ISSUE THREAD

**Issue by githubgirlz** [Fairbanks-io/f5-client#11]
https://www.reddit.com/r/AmItheAsshole/ pretty please?

**Comment by jonfairbanks** [comment]
A scrape job for this has been setup and results are now available at https://f5.news/r/AmItheAsshole.

**Comment by githubgirlz** [comment]
You are absolutely awesome. Is there a way to also show like the last 24 hours? Or is it limited to rising? Thank you soo much!!

**Comment by jonfairbanks** [comment]
This is currently limited to rising posts only, but we'll consider the feedback on adding in a 24 hour option.
